name: gh-pages-deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Build
        run: npm run build
        env:
          NODE_ENV: 'production'

      - name: Deploy
        run: npm run deploy