name: gh-pages-deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
      
      - run: npm install

      - name: Build
        run: npm run build
        env:
          NODE_ENV: 'production'

      - name: Deploy
        run: npm run deploy $GIT_COMMITTER_EMAIL $GIT_COMMITTER_NAME